# Generated by Django 5.1.3 on 2024-12-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=15)),
                ('child_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('program', models.CharField(choices=[('Half-Day', 'Half-Day'), ('Full-Day', 'Full-Day'), ('After School', 'After School')], max_length=50)),
                ('allergies', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
            ],
        ),
    ]
