# Generated by Django 5.1.3 on 2024-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='parent_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='parent_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='program',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='allergies',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='child_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='parent_name',
            field=models.CharField(max_length=255),
        ),
    ]
