# Generated by Django 5.1.3 on 2024-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Babysitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('qualifications', models.TextField()),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('availability', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='babysitters/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
